/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Inventory;

/**
 *
 * @author Happi6
 */
public class Master extends javax.swing.JInternalFrame {

    /**
     * Creates new form Master
     */
    public Master(UI.MDIFrame frame) {
        this.frame = frame;
        initComponents();
        detailedPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox<>();
        dayComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        onHandTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        floatingTable = new javax.swing.JTable();
        overallPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        oldDateValue1 = new javax.swing.JLabel();
        incomingValue1 = new javax.swing.JLabel();
        pulloutValue1 = new javax.swing.JLabel();
        soldValue1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        newDateValue1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        floatingValue1 = new javax.swing.JLabel();
        overallValue1 = new javax.swing.JLabel();
        detailedPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        branchValue = new javax.swing.JLabel();
        productValue = new javax.swing.JLabel();
        beginningValue = new javax.swing.JLabel();
        incomingValue = new javax.swing.JLabel();
        pulloutValue = new javax.swing.JLabel();
        availableValue = new javax.swing.JLabel();
        onHandValue = new javax.swing.JLabel();
        floatingValue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adjustmentValue = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        soldValue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        detailedValue = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Master Inventory");
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(860, 500));

        jLabel13.setText("Date");

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        masterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Branch", "SET", "EXC", "RJC", "AEC", "ST", "CS", "BBS", "GLUTA", "SL 200", "SM 200", "KB 850"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterTable.getTableHeader().setReorderingAllowed(false);
        masterTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                masterTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                masterTableFocusLost(evt);
            }
        });
        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterTable);
        masterTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (masterTable.getColumnModel().getColumnCount() > 0) {
            masterTable.getColumnModel().getColumn(0).setResizable(false);
            masterTable.getColumnModel().getColumn(1).setResizable(false);
            masterTable.getColumnModel().getColumn(2).setResizable(false);
            masterTable.getColumnModel().getColumn(3).setResizable(false);
            masterTable.getColumnModel().getColumn(4).setResizable(false);
            masterTable.getColumnModel().getColumn(5).setResizable(false);
            masterTable.getColumnModel().getColumn(6).setResizable(false);
            masterTable.getColumnModel().getColumn(7).setResizable(false);
            masterTable.getColumnModel().getColumn(8).setResizable(false);
            masterTable.getColumnModel().getColumn(9).setResizable(false);
            masterTable.getColumnModel().getColumn(10).setResizable(false);
            masterTable.getColumnModel().getColumn(11).setResizable(false);
        }

        jTabbedPane1.addTab("Inventory", jScrollPane1);

        onHandTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Branch", "SET", "EXC", "RJC", "AEC", "ST", "CS", "BBS", "GLUTA", "SL 200", "SM 200", "KB 850"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        onHandTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(onHandTable);
        onHandTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (onHandTable.getColumnModel().getColumnCount() > 0) {
            onHandTable.getColumnModel().getColumn(0).setResizable(false);
            onHandTable.getColumnModel().getColumn(1).setResizable(false);
            onHandTable.getColumnModel().getColumn(2).setResizable(false);
            onHandTable.getColumnModel().getColumn(3).setResizable(false);
            onHandTable.getColumnModel().getColumn(4).setResizable(false);
            onHandTable.getColumnModel().getColumn(5).setResizable(false);
            onHandTable.getColumnModel().getColumn(6).setResizable(false);
            onHandTable.getColumnModel().getColumn(7).setResizable(false);
            onHandTable.getColumnModel().getColumn(8).setResizable(false);
            onHandTable.getColumnModel().getColumn(9).setResizable(false);
            onHandTable.getColumnModel().getColumn(10).setResizable(false);
            onHandTable.getColumnModel().getColumn(11).setResizable(false);
        }

        jTabbedPane1.addTab("Stocks on Hand", jScrollPane2);

        floatingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Branch", "SET", "EXC", "RJC", "AEC", "ST", "CS", "BBS", "GLUTA", "SL 200", "SM 200", "KB 850"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        floatingTable.setColumnSelectionAllowed(true);
        floatingTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(floatingTable);
        floatingTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (floatingTable.getColumnModel().getColumnCount() > 0) {
            floatingTable.getColumnModel().getColumn(0).setResizable(false);
            floatingTable.getColumnModel().getColumn(1).setResizable(false);
            floatingTable.getColumnModel().getColumn(2).setResizable(false);
            floatingTable.getColumnModel().getColumn(3).setResizable(false);
            floatingTable.getColumnModel().getColumn(4).setResizable(false);
            floatingTable.getColumnModel().getColumn(5).setResizable(false);
            floatingTable.getColumnModel().getColumn(6).setResizable(false);
            floatingTable.getColumnModel().getColumn(7).setResizable(false);
            floatingTable.getColumnModel().getColumn(8).setResizable(false);
            floatingTable.getColumnModel().getColumn(9).setResizable(false);
            floatingTable.getColumnModel().getColumn(10).setResizable(false);
            floatingTable.getColumnModel().getColumn(11).setResizable(false);
        }

        jTabbedPane1.addTab("Floating Stocks", jScrollPane4);

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("Less:");

        jLabel15.setText("Sold on Date");

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setText("Value on");

        jLabel17.setText("Date");

        jLabel18.setText("Floating Stocks");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Overall Value");

        oldDateValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        oldDateValue1.setText("Value");

        incomingValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        incomingValue1.setText("Value");

        pulloutValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pulloutValue1.setText("Value");

        soldValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        soldValue1.setText("Value");

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel20.setText("Add:");

        newDateValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newDateValue1.setText("Value");

        jLabel21.setText("Date");

        jLabel22.setText("Received Stocks");

        jLabel23.setText("Pulled-out Stocks");

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel24.setText("Less:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel25.setText("Value on");

        floatingValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        floatingValue1.setText("Value");

        overallValue1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        overallValue1.setText("Value");

        javax.swing.GroupLayout overallPanelLayout = new javax.swing.GroupLayout(overallPanel);
        overallPanel.setLayout(overallPanelLayout);
        overallPanelLayout.setHorizontalGroup(
            overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallPanelLayout.createSequentialGroup()
                            .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallPanelLayout.createSequentialGroup()
                                        .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGap(39, 39, 39)
                            .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pulloutValue1)
                                .addComponent(incomingValue1)
                                .addComponent(oldDateValue1)
                                .addComponent(soldValue1)
                                .addComponent(newDateValue1)
                                .addComponent(floatingValue1)
                                .addComponent(overallValue1))
                            .addGap(71, 71, 71))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        overallPanelLayout.setVerticalGroup(
            overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(overallPanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(oldDateValue1)
                        .addComponent(jLabel25))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(incomingValue1)
                        .addComponent(jLabel20))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(pulloutValue1)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soldValue1)
                        .addComponent(jLabel15)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newDateValue1)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16))
                    .addGap(12, 12, 12)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(floatingValue1)
                        .addComponent(jLabel18))
                    .addGap(10, 10, 10)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addGroup(overallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(overallValue1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setText("Branch");

        jLabel2.setText("Product");

        jLabel3.setText("Beginning Stock");

        jLabel4.setText("Incoming Stock");

        jLabel5.setText("Pull Out");

        jLabel6.setText("Available Stock");

        jLabel7.setText("Stocks on hand");

        jLabel8.setText("Floating Stock");

        branchValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        branchValue.setText("Value");

        productValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        productValue.setText("Value");

        beginningValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        beginningValue.setText("Value");

        incomingValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        incomingValue.setText("Value");

        pulloutValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pulloutValue.setText("Value");

        availableValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        availableValue.setText("Value");

        onHandValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        onHandValue.setText("Value");

        floatingValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        floatingValue.setText("Value");

        jLabel9.setText("Adjustments");

        adjustmentValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adjustmentValue.setText("Value");

        jLabel10.setText("Sold");

        soldValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        soldValue.setText("Value");

        jLabel11.setText("Detailed Stock");

        detailedValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        detailedValue.setText("Value");

        javax.swing.GroupLayout detailedPanelLayout = new javax.swing.GroupLayout(detailedPanel);
        detailedPanel.setLayout(detailedPanelLayout);
        detailedPanelLayout.setHorizontalGroup(
            detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))))
                .addGap(41, 41, 41)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adjustmentValue)
                            .addComponent(soldValue)
                            .addComponent(availableValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detailedValue)
                            .addComponent(floatingValue)
                            .addComponent(onHandValue))
                        .addGap(70, 70, 70))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beginningValue)
                            .addComponent(branchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productValue)
                            .addComponent(incomingValue)
                            .addComponent(pulloutValue))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        detailedPanelLayout.setVerticalGroup(
            detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(branchValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(beginningValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(incomingValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pulloutValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(soldValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(adjustmentValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(availableValue)))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(onHandValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floatingValue)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(detailedValue))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(overallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(overallPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_masterTableFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_masterTableFocusGained

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        // TODO add your handling code here:
        detailedPanel.setVisible(true);
        int row = masterTable.getSelectedRow();
        int col = masterTable.getSelectedColumn();
        branchValue.setText("Branch "+row);
        productValue.setText("Product "+col);
    }//GEN-LAST:event_masterTableMouseClicked

    private void masterTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_masterTableFocusLost
        // TODO add your handling code here:
        detailedPanel.setVisible(false);
        
    }//GEN-LAST:event_masterTableFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adjustmentValue;
    private javax.swing.JLabel availableValue;
    private javax.swing.JLabel beginningValue;
    private javax.swing.JLabel branchValue;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JPanel detailedPanel;
    private javax.swing.JLabel detailedValue;
    private javax.swing.JTable floatingTable;
    private javax.swing.JLabel floatingValue;
    private javax.swing.JLabel floatingValue1;
    private javax.swing.JLabel incomingValue;
    private javax.swing.JLabel incomingValue1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable masterTable;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel newDateValue1;
    private javax.swing.JLabel oldDateValue1;
    private javax.swing.JTable onHandTable;
    private javax.swing.JLabel onHandValue;
    private javax.swing.JPanel overallPanel;
    private javax.swing.JLabel overallValue1;
    private javax.swing.JLabel productValue;
    private javax.swing.JLabel pulloutValue;
    private javax.swing.JLabel pulloutValue1;
    private javax.swing.JLabel soldValue;
    private javax.swing.JLabel soldValue1;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables

    private UI.MDIFrame frame;
}
